# Generated by Django 5.1.1 on 2024-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0005_keygroup_alter_privatekey_group_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatekey",
            name="document_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="publickey",
            name="document_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="privatekey",
            constraint=models.UniqueConstraint(
                fields=("private_key", "acct_uuid", "document_number"),
                name="pv_key_acct_doc_num_unique",
                violation_error_message="This key is already tied to this account and document number.",
            ),
        ),
        migrations.AddConstraint(
            model_name="publickey",
            constraint=models.UniqueConstraint(
                fields=("public_key", "acct_uuid", "document_number"),
                name="pb_key_acct_doc_num_unique",
                violation_error_message="This key is already tied to this account and document number.",
            ),
        ),
    ]
